### ISSUE TITLE
Infografia_de_realidad_aumentada

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-abicoronel#1]
[infografia_Realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-abicoronel/files/14270833/infografia_Realidad.aumentada.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by IrvingFernand0** [comment]
Calificación: 20
